-- JOB_INFO 테이블 생성
-- SALARY 는 달러기준
CREATE TABLE JOB_INFO(
    JOB_ID      VARCHAR(10),    -- 직업아이디
    MIN_SALARY  NUMBER,         -- 최저급여
    MAX_SALARY  NUMBER          -- 최고급여
);

INSERT INTO JOB_INFO VALUES('AD_PRES', 20000, 40000);
INSERT INTO JOB_INFO VALUES('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO VALUES('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO VALUES('FI_MGR', 8000, 16000);
INSERT INTO JOB_INFO VALUES('FI_ACCOUNT', 4000, 9000);
INSERT INTO JOB_INFO VALUES('AC_MGR', 8000, 16000);
INSERT INTO JOB_INFO VALUES('AC_ACCOUNT', 4000, 9000);

COMMIT;

SELECT * FROM JOB_INFO;

-- 최저급여, 최고급여의 평균 구하기
SELECT ROUND(AVG(MIN_SALARY), -2) 최저급여평균,
       ROUND(AVG(MAX_SALARY), -2) 최고급여평균
FROM JOB_INFO;

-- 최저급여가 5000이상인 직업 아이디를 검색하시오
/* 실행순서▼
1.FROM
2.WHERE
3.SELECT
4.ORDER
*/
SELECT JOB_ID, MIN_SALARY MIN_SAL
FROM JOB_INFO
WHERE MIN_SALARY >= 5000;
    -- MIN_SAL >= 5000;

-- VIEW로 만들기
-- 최저급여가 5000이상인 정보를 검색한 뷰 생성
CREATE VIEW V_JOB_INFO
AS SELECT *
   FROM JOB_INFO
   WHERE MIN_SALARY >= 5000;
SELECT * FROM V_JOB_INFO;

-- 최고 급여와 최고 급여의 차가 10000이상인 직업아이디를 검색
SELECT JOB_ID
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= 10000;

-- 직업 아이디의 이름이 FI로 시작하는 자료를 검색하시오
SELECT *
FROM V_JOB_INFO
WHERE JOB_ID LIKE 'FI%';

-- MAX_SALARY가 최고인 직업 아이디 검색
SELECT *
FROM V_JOB_INFO
WHERE MAX(max_salary);



SELECT * FROM V_JOB_INFO;

DROP VIEW V_JOB_INFO;
DROP TABLE JOB_INFO;



